config/routes.rb
Rails.application.routes.draw do
  resources :ticket_comments

  #devise_for :users

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :tickets do 
    put "bcc", :action => 'bcc'
    get "users" , :action => 'users'
    member do
      get "tallybytto"
      get "tallybytcreator"
    end
    collection do
      get "popular"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/search/show/:search_params/:page', :controller => :search, :action => 'show'
  post '/search/:search_params/:page', :controller => :search, :action => 'create'
  #
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "tickets#index"
end

app/models/ticket_comment.rb
class TicketComment < ApplicationRecord
  belongs_to :user
  belongs_to :ticket
end

app/controllers/ticket_comments_controller.rb
class TicketCommentsController < ApplicationController
  before_action :get_user

  # GET /ticket_comments/new
  def new
    @ticket_comment = TicketComment.new
    @ticket_id = params[:ticket_id]
  end

  # POST /ticket_comments or /ticket_comments.json
  def create
    @ticket_comment = TicketComment.new(ticket_comment_params.merge(:user_id => @user.id))

    respond_to do |format|
      if @ticket_comment.save
        format.html { redirect_to ticket_url(@ticket_comment.ticket), notice: "Ticket comment was successfully created." }
        format.json { render :show, status: :created, location: @ticket_comment }
      else
        puts @ticket_comment.errors.inspect
        @ticket_id = params[:ticket_id]
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Get user -- needed to leave comments
    def get_user
      redirect_to new_user_session_path and return unless current_user
      @user = current_user
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_comment
      @ticket_comment = TicketComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_comment_params
      params.require(:ticket_comment).permit(:ticket_id, :user_id, :comment)
    end
end

app/helpers/ticket_comments_helper.rb
module TicketCommentsHelper
  def comment_color(current_ticket_count)
    current_ticket_count = 1 unless current_ticket_count 
    color_selector = current_ticket_count % 2 
    ticket_colors = ["white", "gray"] 
    ticket_color = ticket_colors[color_selector] 
    return ticket_color
  end
end

app/views/ticket_comments/_form.html.erb
<div id="new_comment_container">
  <%= form_with(model: ticket_comment) do |form| %>
    <% if ticket_comment.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(ticket_comment.errors.count, "error") %> prohibited this ticket_comment from being saved:</h2>

        <ul>
          <% ticket_comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.hidden_field :ticket_id, :value => @ticket_id %>
    </div>

    <div id="comment_text_container">
      <%= form.label :comment, style: "display: block" %>
      <%= form.text_field :comment %>
    </div>

    <div id="comment_submit_container">
      <%= form.submit 'Leave comment', :class => 'btn' %>
    </div>
  <% end %>
</div>

app/views/ticket_comments/_ticket_comment.html.erb
<div id="<%= dom_id ticket_comment %>" class="ticket_comment <%= comment_color(current_comment_count) %>"> 
  <p>
    <strong>User:</strong>
    <%= ticket_comment.user.email %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= ticket_comment.comment %>
  </p>

</div>

app/views/ticket_comments/edit.html.erb
<h1>Editing ticket comment</h1>

<%= render "form", ticket_comment: @ticket_comment %>

<br>

<div>
  <%= link_to "Show this ticket comment", @ticket_comment %> |
  <%= link_to "Back to ticket comments", ticket_comments_path %>
</div>

app/views/ticket_comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ticket comments</h1>

<div id="ticket_comments">
  <% @ticket_comments.each do |ticket_comment| %>
    <%= render ticket_comment %>
    <p>
      <%= link_to "Show this ticket comment", ticket_comment %>
    </p>
  <% end %>
</div>

<%= link_to "New ticket comment", new_ticket_comment_path %>

app/views/ticket_comments/new.html.erb
<h1>New ticket comment</h1>

<%= render "form", ticket_comment: @ticket_comment %>

<br>

<div>
  <%= link_to "Back to ticket comments", ticket_comments_path %>
</div>

app/views/ticket_comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ticket_comment %>

<div>
  <%= link_to "Edit this ticket comment", edit_ticket_comment_path(@ticket_comment) %> |
  <%= link_to "Back to ticket comments", ticket_comments_path %>

  <%= button_to "Destroy this ticket comment", @ticket_comment, method: :delete %>
</div>