config/routes.rb
Rails.application.routes.draw do
  resources :ticket_comments

  #devise_for :users

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :tickets do 
    put "bcc", :action => 'bcc'
    get "users" , :action => 'users'
    member do
      get "tallybytto"
      get "tallybytcreator"
    end
    collection do
      get "popular"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/search/show/:search_params/:page', :controller => :search, :action => 'show'
  post '/search/:search_params/:page', :controller => :search, :action => 'create'
  #
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "tickets#index"
end

app/models/ticket.rb
WillPaginate.per_page = 5
class Ticket < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :creator, :class_name => "User", :foreign_key => :creator_id
  has_many :ticket_comments

  def to_param
    self.id.to_s + '-' + self.ticket_to + '-' + self.description.parameterize
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy tallybytto tallybytcreator ]

  # GET /tickets or /tickets.json
  def index
    unless params[:page]
      @page = 1 
    else
      @page = params[:page]
    end
    @tickets = Ticket.all.includes(:creator).order(:created_at => :desc).paginate(:page => @page, :per_page => 5)
  end
  
  # GET /tickets or /tickets.json
  def popular
    unless params[:page]
      @page = 1 
    else
      @page = params[:page]
    end
    @tickets = Ticket.all.includes(:creator).order(:cbc_amount => :desc).paginate(:page => @page, :per_page => 5)
  end

  # GET /tickets/1 or /tickets/1.json
  def show
    @ticket_comments = @ticket.ticket_comments.order(:created_at => :desc)
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    if user_signed_in?
      @ticket.creator = current_user 
    else
      @ticket.creator = User.where(:email => 'anonymous@ticketme.com').first
    end
  end

  def users
    @ticket = Ticket.find(params[:ticket_id])
    @users = @ticket.users
  end

  # PUT /tickets/1/bcc
  def bcc
    @ticket = Ticket.find(params[:ticket_id])
    #increase the rank
    if user_signed_in?
      if current_user.tickets.include? @ticket
        flash[:notice] = "You are already watching this ticket."
      else
        current_user.tickets << @ticket 
        @ticket.rank = @ticket.rank + 1
        @ticket.save
        flash[:notice] = "Blind carbon copied this ticket.  It will now show up as one of your watched tickets."
      end
    else
      flash[:notice] = "You must be signed in to BCC a ticket."
    end
    #puts @ticket.to_yaml
    #puts "bcc method"
    redirect_to ticket_path(@ticket)
  end
  
  def tallybytto
    @page = params[:page]
    unless @page
      @page = 1
    end
    @tickets = Ticket.includes(:creator).where(:ticket_to => @ticket.ticket_to).paginate(:page => @page, :per_page => 5)
    @tickets_for_sum = Ticket.where(:ticket_to => @ticket.ticket_to)
    @tally = 0
    for ticket in @tickets_for_sum
      if ticket.cbc_amount.to_f < 1
        @tally = -1
        return
      end
      @tally = @tally + ticket.cbc_amount.to_f 
    end
  end
  
  def tallybytcreator
    @page = params[:page]
    unless @page
      @page = 1
    end
    @tickets = Ticket.includes(:creator).where(:creator => @ticket.creator).paginate(:page => @page, :per_page => 5)
    @tickets_for_sum = Ticket.where(:creator => @ticket.creator)
    @tally = 0
    for ticket in @tickets_for_sum
      if ticket.cbc_amount.to_f < 1
        @tally = -1
        return
      end
      @tally = @tally + ticket.cbc_amount.to_f 
    end
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    creator = current_user #@ticket.creator
    if creator.is_a? User
      @ticket.creator = creator
    else
      @ticket.creator = User.find_by_email('anonymous@ticketme.com')
    end
    respond_to do |format|
      if @ticket.save
        @ticket.users << @ticket.creator
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        puts @ticket.errors
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    @ticket = Ticket.new(ticket_params)
    creator = current_user #@ticket.creator
    unless creator.is_a? User
      @ticket.creator = User.find_by_email('anonymous@ticketme.com')
    end
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created based on the old ticket." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy!

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:ticket_to, :ticket_from, :description, :cbc_amount, :creator_id, :rank, :category_id)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def ticket_color(current_ticket_count)
    current_ticket_count = 1 unless current_ticket_count 
    color_selector = current_ticket_count % 4 
    ticket_colors = ["blue", "red", "green", "yellow"] 
    ticket_color = ticket_colors[color_selector] 
    return ticket_color
  end

  def ticket_tape_version(current_ticket_count)
    current_ticket_count = 1 unless current_ticket_count 
    tape_selector = current_ticket_count % 3 
    ticket_tape = ["top_left", "middle", "top_right"] 
    ticket_tape_select = ticket_tape[tape_selector] 
    return ticket_tape_select
  end
end

app/views/tickets/_form.html.erb
<div id="new-ticket-container">
  <div id="new-ticket-container-sub" >
    <%= form_with(model: ticket, class: "ticket-form") do |form| %>
      <% if ticket.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

          <ul>
            <% ticket.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <table class="new-ticket-table">
        <thead>
          <th></th>
          <th></th>
        </thead>
        <tbody>
          <tr>
            <td colspan="1">
              <div class="new-ticket">
                <%= form.label :ticket_to, style: "display: block" %>
                <%= form.text_field :ticket_to %>
              </div>
            </td>
            <td colspan="1">
              <div class="new-ticket">
                <%= form.label :ticket_from, style: "display: block" %>
                <%= form.text_field :ticket_from %>
              </div>
            </td>
          </tr>
          <tr>
            <td colspan="2">
              <div id="ticket-description" class="new-ticket">
                <%= form.label :description, style: "display: block" %>
                <%= form.text_area :description %>
              </div>
            </td>
          </tr>
          <tr>
            <td>
              <div class="new-ticket">
                <%= form.label :cbc_amount, "Charity based currency amount:", style: "display: block" %>
                <%= form.number_field :cbc_amount %>
              </div>
            </td>
            <td class="empty">
            </td>
          </tr>
          <tr>
            <td class="empty">
              <div class="new-ticket">
                <!-- 
                <%= form.label :creator_id, style: "display: block" %>
                <%= form.number_field :creator_id %>
                -->
              </div>
            </td>
            <td class="empty">
            </td>
          </tr>

        <!--
          <div>
            <%= form.label :rank, style: "display: block" %>
            <%= form.number_field :rank %>
          </div>
        <tr>
          <td colspan="1">
            <div class="new-ticket">
              <%= form.label :category_id, style: "display: block" %>
              <%= form.number_field :category_id %>
            </div>
          </td>
        </tr>
        -->

        </tbody>
      </table>
      <div class="form_button" style="text-align: right">
        <%= form.submit "Create Ticket"   %>
      </div>
    <% end %>
  </div>
</div>

app/views/tickets/_ticket.html.erb
<a href="<%= ticket_path(ticket) %>" class="table-show-ticket">
  <div class="show-ticket-container <%= ticket_color(current_ticket_count) %>">
    <table id="<%= dom_id ticket %>" class="show-ticket">
      <thead>
        <th colspan="2"></th>
        <th></th>
      </thead>
      <tbody>
        <tr>
          <td colspan="1" class="ticket-to">
            <strong>Ticket to:</strong><br/>
            <%= link_to ticket.ticket_to, tallybytto_ticket_path(ticket)  %>
          </td>
          <td class="ticket-from" colspan="1">
            <strong>Ticket from:</strong><br/>
            <%= ticket.ticket_from %>
          </td>
        </tr>
        <tr>
          <td colspan="2" class="ticket-description">
            <strong>Description:</strong><br/>
            <%= ticket.description %>
          </td>
        </tr>
        <tr>
          <td colspan="1">
            <strong>Cbc amount:</strong><br/>
            <% if ticket.cbc_amount.to_f < 1 %>
              <%= Float::INFINITY  %>
            <% else %>
              <%= number_to_currency(ticket.cbc_amount) %>
            <% end %>
          </td>
          <td colspan"1" >
            <strong>Created At:</strong>
            <br/>
            Ticket since <%= time_ago_in_words(ticket.created_at) %> ago
          </td>
        <tr>
          <td colspan="1">
            <strong>Creator:</strong><br/>
            <%= link_to ticket.creator.email, tallybytcreator_ticket_path(ticket)  %>
          </td>
          <td colspan="1">
            <strong>Category:</strong><br/>
            <%= ticket.category_id %>
          </td>
        </tr>
        <tr>
          <td colspan="1">
          </td>
          <td colspan="1">
            <strong>Rank:</strong><br/>
            <%= link_to ticket.rank, ticket_users_path(ticket.id) %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="tape_<%= ticket_tape_version(current_ticket_count) %>">
  </div>
</a>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Show this ticket", @ticket %> |
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tickets</h1>

<div id="tickets">
  <% @tickets.each do |ticket| %>
    <%= render ticket, :current_ticket_count => ticket.id %>
    <div class="bcc_btn_container">
      <%= button_to "BCC: this ticket", ticket_bcc_path(ticket), method: :put, :class => "bcc_ticket" %>
    </div>
    <div class="show_comment_container">
      <%= button_to "Show comments", ticket_path(ticket), :method => :get, :class => 'btn' %>
    </div>
    <div class="ticket-seperator">
      &nbsp;
    </div>
  <% end %>
</div>
<br/>
<div id="paginate_links_container">
  <%= will_paginate @tickets %>
</div>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/popular.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tickets</h1>

<div id="tickets">
  <% @tickets.each do |ticket| %>
    <%= render ticket, :current_ticket_count => ticket.id %>
    <div class="bcc_btn_container">
      <%= button_to "BCC: this ticket", ticket_bcc_path(ticket), method: :put, :class => "bcc_ticket" %>
    </div>
    <div class="show_comment_container">
      <%= button_to "Show comments", ticket_path(ticket), :method => :get, :class => 'btn' %>
    </div>
    <div class="ticket-seperator">
      &nbsp;
    </div>
  <% end %>
</div>
<br/>
<div id="paginate_links_container">
  <%= will_paginate @tickets %>
</div>

app/views/tickets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ticket, :current_ticket_count => @ticket.id %>
<div id="new_based_on_container" >
  <%= button_to "Make a ticket based on this ticket", edit_ticket_path(@ticket), :method => :get, :class => 'btn' %> 

  <!--  <%= button_to "Destroy this ticket", @ticket, method: :delete, :class => "delete-ticket" %> -->
</div>
<%= button_to "Leave a comment", new_ticket_comment_path(:ticket_id => @ticket.id), :method => :get, :class => 'btn', :params => {:ticket_id => @ticket.id } %>
<h1>Comments</h1>
<% i = 0 %>
<div id="ticket_comments_container">
  <% for ticket_comment in @ticket_comments do %>
    <%= render ticket_comment, :partial => 'ticket_comment/_ticket_comment', :current_comment_count => i %>
    <% i = i + 1 %>
  <% end %>
</div>

app/views/tickets/tallybytcreator.html.erb
<div id="tallycreator">
  <h1>Total tally for:</h1>
  <%= @ticket.creator.email %>
  <p>
  The running sum for tickets that have been assigned to that person is:
  <% if @tally.to_f < 1 %>
    <span id="tally_amount"><%= Float::INFINITY.to_s %></span>
  <% else %>
    <span id="tally_amount"><%= number_to_currency(@tally) %></span>
  <% end %>
  </p>
  <br/>
  <br/>
</div>

<h2>From tickets</h2>

<div id="tickets">
  <% @tickets.each do |ticket| %>
    <%= render ticket, :current_ticket_count => ticket.id %>
    <div class="bcc_btn_container">
      <%= button_to "BCC: this ticket", ticket_bcc_path(ticket), method: :put, :class => "bcc_ticket" %>
    </div>
    <div class="show_comment_container">
      <%= button_to "Show comments", ticket_path(ticket), :method => :get, :class => 'btn' %>
    </div>
    <div class="ticket-seperator">
      &nbsp;
    </div>
  <% end %>
</div>
<br/>
<div id="paginate_links_container">
  <%= will_paginate @tickets %>
</div>

app/views/tickets/tallybytto.html.erb
<div id="tallyto">
  <h1>Total tally for:</h1>
  <%= @ticket.ticket_to %>
  <p>
  The running sum for tickets that have been assigned to that person is:
    <% if @tally.to_f < 1 %>
      <span id="tally_amount"><%= Float::INFINITY  %></span>
    <% else %>
      <span id="tally_amount"><%= number_to_currency(@tally) %></span>
    <% end %>
  </p>
  <br/>
  <br/>
</div>
<h2>From tickets</h2>

<div id="tickets">
  <% @tickets.each do |ticket| %>
    <%= render ticket, :current_ticket_count => ticket.id %>
    <div class="bcc_btn_container">
      <%= button_to "BCC: this ticket", ticket_bcc_path(ticket), method: :put, :class => "bcc_ticket" %>
    </div>
    <div class="show_comment_container">
      <%= button_to "Show comments", ticket_path(ticket), :method => :get, :class => 'btn' %>
    </div>
    <div class="ticket-seperator">
      &nbsp;
    </div>
  <% end %>
</div>
<br/>
<div id="paginate_links_container">
  <%= will_paginate @tickets %>
</div>

app/views/tickets/users.html.erb
<%= render @ticket, :current_ticket_count => @ticket.id %>
<br/>
<br/>
<br/>
Users that are watching this ticket.
<% for user in @users %>
  <div class="users">
    <%= user.email %> 
  </div>
<% end %>