config/routes.rb
Rails.application.routes.draw do
  resources :ticket_comments

  #devise_for :users

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :tickets do 
    put "bcc", :action => 'bcc'
    get "users" , :action => 'users'
    member do
      get "tallybytto"
      get "tallybytcreator"
    end
    collection do
      get "popular"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/search/show/:search_params/:page', :controller => :search, :action => 'show'
  post '/search/:search_params/:page', :controller => :search, :action => 'create'
  #
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "tickets#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticketdevil</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="wallpaper">
      &nbsp;
    </div>
    <div id="menu">
      <div id="ticket-devil-logo" class="menu">
          <a id="ticket-devil-logo-link" href="<%= root_path %>">
          Ticketdevil
          </a>
      </div>
        <!-- <div id="ticket-devil-tail">
          <img src="/devil_tail_rt.png" width="188" height="195" />
        </div> -->
      
      <div id="menu-new-ticket-link" class="menu egothic">
        <%= link_to "New ticket", new_ticket_path %>
      </div>

      <div id="menu-popular-link" class="menu egothic">
        <%= link_to "Popular tickets", popular_tickets_path %>
      </div>

      <div id="menu-search-link" class="menu egothic">
        <%= link_to "Search", { :action => 'show', :controller => '/search', :search_params => 'anonymous', :page => 1} %>
      </div>
      
      <div id="menu-browse-link" class="menu egothic">
        <%= link_to "Recent Tickets", root_path %>
      </div>

      <div id="menu-login" class="menu egothic">
        <% if user_signed_in? %>
          <%= link_to "Log Out", destroy_user_session_path, data: {:turbo_method => 'delete'} %>
        <% else %>
          <%= link_to "Log in", new_user_session_path %>
        <% end %>
      </div>

    </div> <!-- end menu id div -->

    <div id="body-container">
      <%= yield %>
    </div>
  </body>
    <script type="text/javascript">
        var windowHeight = document.body.offsetHeight; 
        document.getElementById('wallpaper').style.height = (windowHeight + 75) + "px";
    </script>
</html>